// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsFAbES01RZsdJHR0cc8lK38PJTlr92kE',
    appId: '1:238735075934:web:04c59bb4f2d63d32fb22cf',
    messagingSenderId: '238735075934',
    projectId: 'time-chat-c0e45',
    authDomain: 'time-chat-c0e45.firebaseapp.com',
    storageBucket: 'time-chat-c0e45.firebasestorage.app',
    measurementId: 'G-ZC6EEHEPRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBZQLw9lX1UESDgpwMcgq5n_zrwbe5MJE',
    appId: '1:238735075934:android:466a4885c79b3567fb22cf',
    messagingSenderId: '238735075934',
    projectId: 'time-chat-c0e45',
    storageBucket: 'time-chat-c0e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALG16i9SZzUUs9D4YlWnIRt00oPKDQ8kU',
    appId: '1:238735075934:ios:8b3d19b345c8a59bfb22cf',
    messagingSenderId: '238735075934',
    projectId: 'time-chat-c0e45',
    storageBucket: 'time-chat-c0e45.firebasestorage.app',
    iosBundleId: 'com.example.timeChat',
  );
}
